import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";

const raleway = Raleway({ subsets: ["latin"] });

import Navbar from "@/components/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='light'>
      <body className={raleway.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
